Repository RevenueCat/purchases-js, pull requests merged in 2024-12, with the labels that each got.

#251 Added svelte to prettier
  .prettierrc
  package-lock.json
  package.json
  src/helpers/paywall-variables-helpers.ts
  src/helpers/price-labels.ts
  src/stories/purchase-flow.stories.svelte
  src/stories/state-error.stories.svelte
  src/stories/state-loading.stories.svelte
  src/stories/state-needs-auth-info.stories.svelte
  src/stories/state-needs-payment-info.stories.svelte
  src/stories/state-present-offer.stories.svelte
  src/stories/state-success.stories.svelte
  src/stories/utils/with-context.svelte
  src/ui/app-icon.svelte
  src/ui/branding-info-ui.svelte
  src/ui/icons/icon-cart.svelte
  src/ui/icons/icon-error.svelte
  src/ui/icons/icon-lock.svelte
  src/ui/icons/icon-success.svelte
  src/ui/layout/aside-block.svelte
  src/ui/layout/container.svelte
  src/ui/layout/layout.svelte
  src/ui/layout/main-block.svelte
  src/ui/layout/message-layout.svelte
  src/ui/localization/localized.svelte
  src/ui/modal.svelte
  src/ui/processing-animation.svelte
  src/ui/rcb-ui.svelte
  src/ui/sandbox-banner.svelte
  src/ui/spinner.svelte
  src/ui/states/state-error.svelte
  src/ui/states/state-loading.svelte
  src/ui/states/state-needs-auth-info.svelte
  src/ui/states/state-needs-payment-info.svelte
  src/ui/states/state-present-offer.svelte
  src/ui/states/state-success.svelte
Labels: pr:dependencies

#249 adds husky pre-commit hook to auto fix linting and formatting
  .husky/pre-commit
  package-lock.json
  package.json
Labels: pr:other

#250 [ECO-1783] Rename RCBillingAppConfig properties
  examples/rcbilling-demo/package-lock.json
  examples/rcbilling-demo/src/tests/main.test.ts
  src/networking/responses/branding-response.ts
  src/stories/fixtures.ts
  src/tests/test-responses.ts
  src/ui/branding-info-ui.svelte
  src/ui/rcb-ui.svelte
  src/ui/states/state-needs-payment-info.svelte
Labels: pr:other

#252 adds test for puchase flow using rc_paywalls
  examples/rcbilling-demo/src/tests/main.test.ts
Labels: pr:other

#248 fix: Improve payment method validation by displaying Stripe errors in the form when possible
  src/entities/errors.ts
  src/helpers/purchase-operation-helper.ts
  src/ui/button.svelte
  src/ui/layout/message-layout.svelte
  src/ui/rcb-ui.svelte
  src/ui/states/state-error.svelte
  src/ui/states/state-needs-payment-info.svelte
Labels: pr:fix

#254 adds e2e for variable replacement
  examples/rcbilling-demo/src/tests/main.test.ts
Labels: pr:other

#256 ECO-1797: PR to fix price conversions in different languages.
  src/helpers/paywall-variables-helpers.ts
  src/stories/state-present-offer.stories.svelte
  src/tests/locale/locale.test.ts
  src/ui/localization/translator.ts
  src/ui/states/state-present-offer.svelte
Labels: pr:fix

#257 Update purchase-params.ts
  api-report/purchases-js.api.json
  src/entities/purchase-params.ts
Labels: pr:fix

#255 chore: Publish storybook in Chromatic
  .circleci/config.yml
  .storybook/main.ts
  README.md
  package-lock.json
  package.json
  src/stories/fixtures.ts
  src/stories/purchase-flow.stories.svelte
  src/stories/state-needs-payment-info.stories.svelte
  src/stories/utils/purchase-response-builder.ts
  src/stories/utils/state-needs-payment-info-with-purchase-response.svelte
Labels: pr:other

#265 Update fastlane plugin to include some fixes and some other dependencies
  Gemfile.lock
Labels: pr:other

#264 Release/0.14.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  package.json
  scripts/docs/index.html
  src/helpers/constants.ts
Labels: pr:next_release

#258 upgrade dependencies
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/rcbilling-demo/package-lock.json
  examples/rcbilling-demo/package.json
  package-lock.json
  package.json
  src/tests/helpers/paywall-variables-helper.test.ts
  svelte.config.js
  vite.config.js
  vitest.config.js
Labels: pr:other, pr:next_release, pr:RevenueCatUI

#263 [DO NOT MERGE] add onError callback that rejects the promise of the rendering
  src/main.ts
Labels: pr:other

#260 feat: Added Support for Direct Payment Flow
  README.md
  examples/rcbilling-demo/src/tests/main.test.ts
  src/networking/backend.ts
  src/stories/state-needs-payment-info.stories.svelte
  src/stories/utils/purchase-response-builder.ts
  src/stories/utils/state-needs-payment-info-with-purchase-response.svelte
  src/tests/networking/backend.test.ts
  src/ui/states/state-needs-payment-info.svelte
Labels: pr:feat

#267 Fix for the select options background color on windows
  src/stories/purchase-flow.stories.svelte
  src/ui/states/state-needs-payment-info.svelte
  src/ui/theme/colors.ts
Labels: bug, pr:fix
