Repository RevenueCat/purchases-js, pull requests merged in 2024-07, with the labels that each got.

#142 Update storybook to fix security concern
  examples/rcbilling-demo/package-lock.json
  package-lock.json
Labels: dependencies

#143 Add backend email validation errors display to email screen
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/entities/errors.ts
  src/helpers/purchase-operation-helper.ts
  src/ui/rcb-ui.svelte
  src/ui/states/state-needs-auth-info.svelte
Labels: refactor

#146 [EXTERNAL] Fix storybook development mode (#145) contributed by @AbraaoAlves
  src/ui/rcb-ui.svelte
  src/ui/states/state-present-offer.svelte
Labels: fix

#147 Add support for adding additional headers on http requests
  README.md
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/entities/http-config.ts
  src/main.ts
  src/networking/backend.ts
  src/networking/http-client.ts
  src/tests/networking/backend.test.ts
Labels: feat

#148 Add support for `proxyURL` to redirect requests
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/entities/http-config.ts
  src/helpers/configuration-validators.ts
  src/main.ts
  src/networking/endpoints.ts
  src/networking/http-client.ts
  src/tests/networking/endpoints.test.ts
Labels: feat

#150 [Behavior change] Fail configuration if trying to add additional headers that are reserved for SDK
  src/helpers/configuration-validators.ts
  src/main.ts
  src/networking/http-client.ts
  src/tests/main.test.ts
Labels: refactor

#151 Change modal border radius to 16px
  src/ui/modal.svelte
Labels: enhancement, refactor, style

#154 Update api-extractor and only diff markdown file for api tests
  .circleci/config.yml
  examples/rcbilling-demo/package-lock.json
  package-lock.json
  package.json
Labels: refactor
