Repository RevenueCat/purchases-js, pull requests merged in 2024-11, with the labels that each got.

#228 fix: Adjust the default luminance threshold from 0.2 to 0.37
  src/ui/theme/utils.ts
Labels: pr:other

#229 Change purchase API to avoid breaking change
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/rcbilling-demo/src/pages/paywall/index.tsx
  src/entities/purchase-result.ts
  src/main.ts
Labels: pr:fix

#226 ECO-1595: Bumping to svelte 5 for the upcoming purchases-ui-web
  .circleci/config.yml
  .storybook/main.ts
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/rcbilling-demo/.gitignore
  examples/rcbilling-demo/package-lock.json
  package-lock.json
  package.json
  src/helpers/offerings-parser.ts
  src/main.ts
  src/stories/purchases-ui-web.stories.svelte
  src/tests/test-responses.ts
  src/ui/states/state-error.svelte
  tsconfig.json
  vitest.config.js
Labels: pr:dependencies

#235 Add convenience method to generate RC-like anonymous IDs
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/rcbilling-demo/src/pages/login/index.tsx
  package-lock.json
  src/main.ts
  src/tests/main.test.ts
Labels: pr:feat

#227 ECO-1606: @internal @experimental renderPaywall method
  README.md
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/rcbilling-demo/README.md
  examples/rcbilling-demo/package-lock.json
  examples/rcbilling-demo/package.json
  examples/rcbilling-demo/src/App.css
  examples/rcbilling-demo/src/App.tsx
  examples/rcbilling-demo/src/pages/rc_paywall/index.tsx
  examples/rcbilling-demo/src/tests/main.test.ts
  package-lock.json
  package.json
  src/entities/offerings.ts
  src/entities/render-paywall-params.ts
  src/main.ts
  src/networking/responses/offerings-response.ts
  src/tests/purchase.offerings.test.ts
  src/tests/test-responses.ts
  src/ui/theme/constants.ts
Labels: pr:feat

#236 Remove logout button from the paywall page in the demo app
  examples/rcbilling-demo/src/pages/rc_paywall/index.tsx
Labels: pr:fix

#237 Removing the lateral padding based on screen width only
  src/ui/layout/layout.svelte
Labels: pr:fix

#239 Migrated all dependencies into devDependencies since we build a UMD package
  examples/rcbilling-demo/package-lock.json
  package-lock.json
  package.json
  src/stories/purchases-ui-web.stories.svelte
Labels: pr:dependencies

#234 Change "plan" to "subscription" on success page copy
  src/ui/states/state-success.svelte
Labels: pr:other

#240 Eco 1701 rcbpurchui pass the variables from the sdk to the paywall
  package-lock.json
  package.json
  src/entities/offerings.ts
  src/entities/render-paywall-params.ts
  src/helpers/paywall-variables-helpers.ts
  src/helpers/price-labels.ts
  src/main.ts
  src/tests/helpers/paywall-variables-helper.test.ts
Labels: pr:feat, next_release

#245 fix: disable the submit button until the payment details are set
  src/ui/states/state-needs-payment-info.svelte
Labels: pr:other
