Repository RevenueCat/purchases-js, pull requests merged in 2024-08, with the labels that each got.

#152 Add `presentedOfferingContext` type to include all context information
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/entities/offerings.ts
  src/helpers/purchase-operation-helper.ts
  src/main.ts
  src/networking/backend.ts
  src/networking/responses/offerings-response.ts
  src/tests/helpers/purchase-operation-helper.test.ts
  src/tests/main.test.ts
  src/tests/mocks/offering-mock-provider.ts
  src/tests/networking/backend.test.ts
  src/tests/test-responses.ts
  src/ui/rcb-ui.svelte
Labels: feat

#160 Improve formatted price calculation
  examples/rcbilling-demo/src/tests/main.test.ts
  src/helpers/price-labels.ts
  src/tests/helpers/price-labels.test.ts
  src/ui/states/state-present-offer.svelte
Labels: refactor

#164 Make main CTA not say "Pay" if the customer is starting a trial
  examples/rcbilling-demo/src/tests/main.test.ts
  src/ui/button.svelte
  src/ui/rcb-ui.svelte
  src/ui/states/state-needs-payment-info.svelte
Labels: feat

#161 [Beta] Support different currencies
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/entities/get-offerings-params.ts
  src/entities/offerings.ts
  src/helpers/purchase-operation-helper.ts
  src/helpers/validators.ts
  src/main.ts
  src/networking/backend.ts
  src/networking/endpoints.ts
  src/networking/responses/products-response.ts
  src/tests/helpers/purchase-operation-helper.test.ts
  src/tests/main.test.ts
  src/tests/mocks/offering-mock-provider.ts
  src/tests/networking/backend.test.ts
  src/tests/test-responses.ts
  src/ui/rcb-ui.svelte
  src/ui/states/state-present-offer.svelte
Labels: feat

#167 ECO-1398: Added the possibility to pass a currency in the demo app query string params
  examples/rcbilling-demo/src/pages/paywall/index.tsx
  examples/rcbilling-demo/src/util/PurchasesLoader.ts
Labels: test
