Repository RevenueCat/purchases-js, pull requests merged in 2024-06, with the labels that each got.

#121 Add `title` and `description` to Product
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/entities/offerings.ts
  src/networking/responses/products-response.ts
  src/tests/main.test.ts
  src/tests/test-responses.ts
Labels: feat

#120 Update vite dependency in RCBilling demo app
  examples/rcbilling-demo/package-lock.json
  examples/rcbilling-demo/package.json
Labels: test

#123 Add processed `period` to `PricingPhase`
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/entities/offerings.ts
  src/helpers/duration-helper.ts
  src/main.ts
  src/tests/main.test.ts
Labels: refactor

#124 Add new `OfferNotFound` error parsing to backend request error processing
  src/entities/errors.ts
  src/tests/networking/backend.test.ts
Labels: refactor

#125 Small demo app changes
  examples/rcbilling-demo/index.html
  examples/rcbilling-demo/public/vite.svg
  examples/rcbilling-demo/src/pages/login/index.tsx
Labels: docs

#126 Make demo app independent of entitlement ID
  examples/rcbilling-demo/package-lock.json
  examples/rcbilling-demo/src/App.tsx
  examples/rcbilling-demo/src/components/WithEntitlement.tsx
  examples/rcbilling-demo/src/components/WithoutEntitlement.tsx
  package-lock.json
Labels: docs

#133 Show better errors in purchase flow when user is subscribed
  src/entities/errors.ts
  src/helpers/purchase-operation-helper.ts
  src/tests/helpers/purchase-operation-helper.test.ts
  src/ui/rcb-ui.svelte
  src/ui/states/state-error.svelte
Labels: refactor

#135 Validate email in SDK
  src/helpers/validators.ts
  src/tests/helpers/validators.test.ts
  src/ui/states/state-needs-auth-info.svelte
Labels: refactor

#138 Fix side info not showing when not specifying purchase option
  src/ui/rcb-ui.svelte
Labels: fix
