Repository RevenueCat/purchases-js, pull requests merged in 2024-10, with the labels that each got.

#195 Update fastlane plugin
  Gemfile.lock
Labels: pr:other

#191 Support non renewable products.
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/rcbilling-demo/src/tests/main.test.ts
  src/entities/errors.ts
  src/entities/offerings.ts
  src/main.ts
  src/networking/responses/products-response.ts
  src/tests/mocks/offering-mock-provider.ts
  src/tests/purchase.offerings.test.ts
  src/tests/test-responses.ts
Labels: pr:feat

#193 Update UI to support consumables and non consumables
  src/ui/rcb-ui.svelte
  src/ui/states/state-present-offer.svelte
  src/ui/states/state-success.svelte
Labels: pr:other

#194 Change endpoint to use the new `/purchase`
  examples/rcbilling-demo/src/tests/main.test.ts
  src/helpers/purchase-operation-helper.ts
  src/networking/backend.ts
  src/networking/endpoints.ts
  src/networking/responses/purchase-response.ts
  src/tests/helpers/purchase-operation-helper.test.ts
  src/tests/networking/backend.test.ts
  src/tests/networking/endpoints.test.ts
  src/ui/rcb-ui.svelte
  src/ui/states/state-needs-payment-info.svelte
Labels: pr:other

#171 Eco 1307 sdk pull customization data from the backend endpoint
  examples/rcbilling-demo/package-lock.json
  examples/rcbilling-demo/src/util/PurchasesLoader.ts
  global.d.ts
  package-lock.json
  package.json
  src/helpers/process-style-overrides.ts
  src/main.ts
  src/networking/responses/branding-response.ts
  src/store/store.ts
  src/ui/assets/icon-lock.svelte
  src/ui/assets/icon-success.svelte
  src/ui/button.svelte
  src/ui/rcb-ui.svelte
  src/ui/states/state-needs-auth-info.svelte
Labels: pr:feat

#200 Fix error message purchasing already purchased non-consumables
  examples/rcbilling-demo/package-lock.json
  package-lock.json
  src/entities/errors.ts
  src/helpers/purchase-operation-helper.ts
  src/tests/helpers/purchase-operation-helper.test.ts
  src/ui/rcb-ui.svelte
  src/ui/states/state-error.svelte
Labels: pr:fix

#201 Add support for getting a single offering
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/rcbilling-demo/src/pages/paywall/index.tsx
  examples/rcbilling-demo/src/tests/main.test.ts
  examples/rcbilling-demo/src/util/PurchasesLoader.ts
  src/entities/get-offerings-params.ts
  src/entities/offerings.ts
  src/main.ts
  src/tests/purchase.offerings.test.ts
Labels: pr:feat

#204 Adds fastlane/.env.SAMPLE
  fastlane/.env.SAMPLE
Labels: pr:other

#206 ECO-1336: Revamping storybook to make it easier to implement UI changes in the sdk
  .gitignore
  .storybook/main.ts
  package-lock.json
  package.json
  src/stories/PaymentModal.stories.ts
  src/stories/state-present-offer.stories.svelte
Labels: pr:dependencies

#207 ECO-1336-layout components
  src/stories/state-present-offer.stories.svelte
  src/ui/layout/aside-block.svelte
  src/ui/layout/container.svelte
  src/ui/layout/layout.svelte
  src/ui/layout/main-block.svelte
  src/ui/rcb-ui.svelte
Labels: pr:other

#210 Fix locale to 'en'
  src/ui/states/state-needs-payment-info.svelte
Labels: pr:fix

#209 Customization: Added shapes, background colors and generated text color.
  examples/rcbilling-demo/package-lock.json
  src/assets/cart.svg
  src/assets/colors.ts
  src/assets/error.svg
  src/assets/lock.svg
  src/assets/spinner.gif
  src/assets/spinner.svg
  src/assets/success.svg
  src/helpers/process-style-overrides.ts
  src/main.ts
  src/store/store.ts
  src/stories/fixtures.ts
  src/stories/purchase-flow.stories.svelte
  src/stories/state-error.stories.svelte
  src/stories/state-loading.stories.svelte
  src/stories/state-needs-auth-info.stories.svelte
  src/stories/state-needs-payment-info.stories.svelte
  src/stories/state-present-offer.stories.svelte
  src/stories/state-success.stories.svelte
  src/ui/assets/icon-cart.svelte
  src/ui/assets/icon-error.svelte
  src/ui/assets/icon-lock.svelte
  src/ui/assets/icon-success.svelte
  src/ui/button.svelte
  src/ui/close-button.svelte
  src/ui/icons/icon-cart.svelte
  src/ui/icons/icon-error.svelte
  src/ui/icons/icon-lock.svelte
  src/ui/icons/icon-success.svelte
  src/ui/layout/aside-block.svelte
  src/ui/layout/main-block.svelte
  src/ui/layout/message-layout.svelte
  src/ui/modal.svelte
  src/ui/rcb-ui.svelte
  src/ui/sandbox-banner.svelte
  src/ui/shell.svelte
  src/ui/spinner.svelte
  src/ui/states/state-error.svelte
  src/ui/states/state-loading.svelte
  src/ui/states/state-needs-auth-info.svelte
  src/ui/states/state-needs-payment-info.svelte
  src/ui/states/state-success.svelte
  src/ui/theme/colors.ts
  src/ui/theme/shapes.ts
  src/ui/theme/theme.ts
  src/ui/theme/utils.ts
  src/ui/transaction-overview.svelte
Labels: pr:feat

#211 Fix security vulnerabilities
  package-lock.json
Labels: pr:dependencies

#212 Customisation: Toggle product description from the product info panel
  src/stories/fixtures.ts
  src/stories/state-present-offer.stories.svelte
  src/ui/rcb-ui.svelte
  src/ui/states/state-present-offer.svelte
Labels: pr:feat

#215 Restored the default accent and focus colors used before the customization implementation
  src/ui/theme/colors.ts
Labels: pr:fix

#213 Demo App: Allow using anonymous IDs and generate deep links on demo app
  examples/rcbilling-demo/package-lock.json
  examples/rcbilling-demo/package.json
  examples/rcbilling-demo/src/pages/login/index.tsx
  examples/rcbilling-demo/src/pages/success/index.tsx
Labels: pr:other

#217 Fix handling unrecognized error codes in purchase operation
  src/helpers/purchase-operation-helper.ts
  src/networking/responses/checkout-status-response.ts
  src/tests/helpers/purchase-operation-helper.test.ts
Labels: pr:fix

#221 fix: Typo in the default accent color
  src/stories/state-needs-payment-info.stories.svelte
  src/ui/theme/colors.ts
Labels: pr:fix, pr:RevenueCatUI

#220 [ECO-1560] Add redemption info data on status response
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/rcbilling-demo/package-lock.json
  examples/rcbilling-demo/src/pages/paywall/index.tsx
  examples/rcbilling-demo/src/pages/success/index.tsx
  src/entities/get-offerings-params.ts
  src/entities/purchase-result.ts
  src/entities/redemption-info.ts
  src/helpers/purchase-operation-helper.ts
  src/main.ts
  src/networking/responses/checkout-status-response.ts
  src/tests/helpers/purchase-operation-helper.test.ts
  src/ui/rcb-ui.svelte
Labels: pr:feat, pr:breaking

#224 Customization: Aligned luminance with the one in the Customer Portal and the WPL
  src/ui/theme/utils.ts
Labels: pr:fix
