Repository RevenueCat/purchases-js, pull requests merged in 2025-07, with the labels that each got.

#538 Prefer provided email for wallet payments
  src/ui/pages/payment-entry-page.svelte
Labels: pr:feat, codex

#543 Add controls to PricingSummary stories
  src/stories/molecules/pricing-summary.stories.svelte
Labels: pr:other, codex

#546 Add store transaction info to purchase result
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/webbilling-demo/package-lock.json
  examples/webbilling-demo/src/pages/paywall/index.tsx
  package-lock.json
  src/entities/purchase-result.ts
  src/entities/store-transaction.ts
  src/helpers/purchase-operation-helper.ts
  src/main.ts
  src/networking/responses/checkout-status-response.ts
  src/tests/helpers/purchase-operation-helper.test.ts
  src/tests/ui/purchases-ui.test.ts
  src/ui/purchases-ui.svelte
Labels: pr:feat

#549 From ZD ticket
  examples/webbilling-demo/README.md
Labels: documentation, pr:other

#542 preload stripe again
  src/stripe/stripe-service.ts
Labels: enhancement, pr:other

#554 feat: refactor purchase options and update payment terms across all localizations
  src/stories/molecules/secure-checkout-rc.stories.svelte
  src/ui/localization/keys_context.json
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/molecules/secure-checkout-rc.svelte
  src/ui/pages/payment-entry-page.svelte
Labels: pr:fix
