Repository RevenueCat/purchases-js, pull requests merged in 2025-06, with the labels that each got.

#515 Fire CheckoutPaymentFormImpression event only when stripe loaded
  src/tests/ui/pages/payment-entry-page.test.ts
  src/ui/pages/payment-entry-page.svelte
Labels: pr:other

#522 Fix customElements not defined error
  package-lock.json
  package.json
Labels: pr:fix, dependencies

#524 Fixed an issue with Apple Pay when the passed date can get outdated between calculation and click
  examples/webbilling-demo/package-lock.json
  src/stories/fixtures.ts
  src/stripe/stripe-service.ts
  src/tests/stripe/stripe-service.test.ts
Labels: pr:fix

#528 Update fixture
  examples/webbilling-demo/src/tests/helpers/fixtures.ts
Labels: pr:other

#531 Internally track embedded usages
  examples/webbilling-demo/package-lock.json
  examples/webbilling-demo/src/util/PurchasesLoader.ts
  src/entities/flags-config.ts
  src/main.ts
  src/tests/base.purchases_test.ts
  src/tests/main.test.ts
Labels: pr:feat

#530 [WEB-2744] Add object-based configuration for Purchases SDK initialization
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/webbilling-demo/src/util/PurchasesLoader.ts
  src/entities/purchases-config.ts
  src/main.ts
  src/tests/main.test.ts
Labels: pr:feat
