Repository RevenueCat/purchases-js, pull requests merged in 2025-02, with the labels that each got.

#290 [WEB-2051] Fix displaying error message upon failing email format validation
  examples/rcbilling-demo/package-lock.json
  package-lock.json
  package.json
  src/tests/ui/purchases-ui.test.ts
  src/ui/states/state-needs-auth-info.svelte
Labels: bug, pr:fix

#291 Separate event helpers
  examples/rcbilling-demo/src/tests/main.test.ts
  src/behavioural-events/event-helpers.ts
  src/behavioural-events/event.ts
  src/behavioural-events/events-tracker.ts
  src/behavioural-events/events.ts
  src/behavioural-events/tracked-events.ts
  src/main.ts
  src/tests/behavioral-events/events-tracker.test.ts
  src/tests/behavioral-events/flush-manager.test.ts
  src/tests/purchase.events.ts
  src/tests/ui/purchases-ui.test.ts
  src/ui/rcb-ui.svelte
  src/ui/states/state-needs-auth-info.svelte
Labels: pr:other

#292 [WEB-2053] Add an internal public function to track events from WPL
  examples/rcbilling-demo/package-lock.json
  package-lock.json
  src/main.ts
  src/tests/main.test.ts
Labels: pr:other

#293 [WEB-1912] Add customerEmailProvided property to CheckoutSessionStart event
  src/behavioural-events/event-helpers.ts
  src/behavioural-events/tracked-events.ts
  src/tests/ui/purchases-ui.test.ts
  src/ui/rcb-ui.svelte
Labels: pr:other

#295 [WEB-1915] Track purchase successful events
  src/behavioural-events/event-helpers.ts
  src/behavioural-events/events-tracker.ts
  src/behavioural-events/sdk-events.ts
  src/main.ts
  src/stories/fixtures.ts
  src/stories/purchase-flow.stories.svelte
  src/stories/state-needs-auth-info.stories.svelte
  src/stories/state-needs-payment-info.stories.svelte
  src/stories/state-present-offer.stories.svelte
  src/stories/state-success.stories.svelte
  src/tests/behavioral-events/events-tracker.test.ts
  src/tests/main.test.ts
  src/tests/ui/purchases-ui.test.ts
  src/ui/layout/message-layout.svelte
  src/ui/rcb-ui.svelte
  src/ui/states/state-error.svelte
  src/ui/states/state-needs-auth-info.svelte
  src/ui/states/state-needs-payment-info.svelte
  src/ui/states/state-success.svelte
Labels: pr:other

#301 Fix some alignments / Rename Modal
  package-lock.json
  src/stories/purchase-flow-desktop.stories.svelte
  src/stories/purchase-flow-mobile.stories.svelte
  src/ui/layout/main-block.svelte
  src/ui/layout/message-layout.svelte
  src/ui/layout/navbar.svelte
  src/ui/layout/section-layout.svelte
  src/ui/modal.svelte
  src/ui/theme/spacing.ts
Labels: pr:other

#298 [WEB-2001] Add context to events
  examples/rcbilling-demo/src/tests/main.test.ts
  src/behavioural-events/event-context.ts
  src/behavioural-events/event.ts
  src/tests/behavioral-events/event-context.test.ts
  src/tests/behavioral-events/events-tracker.test.ts
  src/tests/purchase.events.test.ts
Labels: pr:other

#306 Minor updates to user events
  examples/rcbilling-demo/src/tests/main.test.ts
  src/behavioural-events/event-helpers.ts
  src/behavioural-events/sdk-events.ts
  src/main.ts
  src/tests/purchase.events.test.ts
  src/tests/ui/purchases-ui.test.ts
  src/tests/ui/states/state-needs-auth-info.test.ts
  src/tests/ui/states/state-needs-payment-info.test.ts
  src/tests/ui/states/state-success.test.ts
  src/ui/rcb-ui.svelte
  src/ui/states/state-needs-auth-info.svelte
  src/ui/states/state-needs-payment-info.svelte
  src/ui/states/state-success.svelte
Labels: pr:other

#299 [WEB-2056] Use a different domain for event tracking
  .env.development
  .env.production
  .env.test
  examples/rcbilling-demo/src/tests/main.test.ts
  src/behavioural-events/events-tracker.ts
  src/helpers/constants.ts
  src/main.ts
Labels: pr:other

#308 Remove redundant event fields
  examples/rcbilling-demo/src/tests/main.test.ts
  src/behavioural-events/event-context.ts
  src/tests/behavioral-events/event-context.test.ts
Labels: pr:other

#307 Calculate button states
  package.json
  src/stories/components.stories.svelte
  src/stories/fixtures.ts
  src/tests/theme/utils.test.ts
  src/ui/button.svelte
  src/ui/theme/colors.ts
  src/ui/theme/utils.ts
Labels: pr:other

#310 Flatten event payload
  examples/rcbilling-demo/src/tests/main.test.ts
  src/behavioural-events/event-context.ts
  src/behavioural-events/event.ts
  src/behavioural-events/events-tracker.ts
  src/behavioural-events/flush-manager.ts
  src/behavioural-events/sdk-event-context.ts
  src/behavioural-events/sdk-event-helpers.ts
  src/behavioural-events/sdk-events.ts
  src/main.ts
  src/tests/behavioral-events/events-tracker.test.ts
  src/tests/behavioral-events/flush-manager.test.ts
  src/tests/behavioral-events/sdk-event-context.test.ts
  src/tests/main.test.ts
  src/tests/purchase.events.test.ts
  src/ui/rcb-ui.svelte
  src/ui/states/state-needs-auth-info.svelte
  src/ui/states/state-needs-payment-info.svelte
Labels: pr:other

#281 WEB-1998: Allow metadata to be sent at purchase
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/webbilling-demo/src/tests/main.test.ts
  examples/webbilling-demo/src/util/PurchasesLoader.ts
  src/entities/flags-config.ts
  src/entities/offerings.ts
  src/entities/purchase-params.ts
  src/helpers/purchase-operation-helper.ts
  src/helpers/utm-params.ts
  src/main.ts
  src/networking/backend.ts
  src/tests/helpers/utm-params.test.ts
  src/ui/rcb-ui.svelte
Labels: pr:feat

#312 [WEB-2082] Append `trace_Id` and `checkout_session_id` to returned redeemUrl
  src/behavioural-events/events-tracker.ts
  src/main.ts
  src/tests/purchase.test.ts
Labels: pr:other

#313 [WEB-2082] Forward `trace_id` and `checkout_session_id` to start purchase
  src/behavioural-events/events-tracker.ts
  src/helpers/purchase-operation-helper.ts
  src/main.ts
  src/networking/backend.ts
  src/tests/helpers/purchase-operation-helper.test.ts
  src/tests/networking/backend.test.ts
Labels: pr:other

#315 Some UI fixes
  src/helpers/paywall-variables-helpers.ts
  src/stories/fixtures.ts
  src/stories/purchase-flow-desktop.stories.svelte
  src/stories/purchase-flow-mobile.stories.svelte
  src/ui/badge.svelte
  src/ui/icons/icon-arrow.svelte
  src/ui/localization/locale/en.json
  src/ui/states/state-needs-auth-info.svelte
  src/ui/states/state-present-offer.svelte
  src/ui/theme/text.ts
Labels: pr:other

#318 Remove checkout_session_id
  examples/webbilling-demo/src/tests/main.test.ts
  src/behavioural-events/event.ts
  src/behavioural-events/events-tracker.ts
  src/helpers/purchase-operation-helper.ts
  src/main.ts
  src/networking/backend.ts
  src/stories/fixtures.ts
  src/tests/behavioral-events/events-tracker.test.ts
  src/tests/helpers/purchase-operation-helper.test.ts
  src/tests/mocks/events-tracker-mock-provider.ts
  src/tests/networking/backend.test.ts
  src/tests/purchase.events.test.ts
Labels: pr:other

#302 User events
  .circleci/config.yml
  .env.development
  .env.production
  .env.test
  Gemfile.lock
  README.md
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/webbilling-demo/package-lock.json
  examples/webbilling-demo/src/tests/main.test.ts
  package-lock.json
  package.json
  src/behavioural-events/event.ts
  src/behavioural-events/events-tracker.ts
  src/behavioural-events/flush-manager.ts
  src/behavioural-events/sdk-event-context.ts
  src/behavioural-events/sdk-event-helpers.ts
  src/behavioural-events/sdk-events.ts
  src/entities/http-config.ts
  src/entities/purchase-result.ts
  src/helpers/camel-to-underscore.ts
  src/helpers/constants.ts
  src/helpers/purchase-operation-helper.ts
  src/main.ts
  src/networking/backend.ts
  src/networking/http-client.ts
  src/stories/fixtures.ts
  src/stories/purchase-flow.stories.svelte
  src/stories/state-needs-auth-info.stories.svelte
  src/stories/state-needs-payment-info.stories.svelte
  src/stories/state-present-offer.stories.svelte
  src/stories/state-success.stories.svelte
  src/tests/base.purchases_test.ts
  src/tests/behavioral-events/events-tracker.test.ts
  src/tests/behavioral-events/flush-manager.test.ts
  src/tests/behavioral-events/sdk-event-context.test.ts
  src/tests/entities/customer-info.test.ts
  src/tests/helpers/purchase-operation-helper.test.ts
  src/tests/main.test.ts
  src/tests/mocks/events-tracker-mock-provider.ts
  src/tests/networking/backend.test.ts
  src/tests/purchase.events.test.ts
  src/tests/test-responses.ts
  src/tests/ui/purchases-ui.test.ts
  src/tests/ui/states/state-needs-auth-info.test.ts
  src/tests/ui/states/state-needs-payment-info.test.ts
  src/tests/ui/states/state-success.test.ts
  src/tests/utils/to-have-been-called-exactly-once-with.ts
  src/tests/vitest.d.ts
  src/ui/close-button.svelte
  src/ui/constants.ts
  src/ui/layout/message-layout.svelte
  src/ui/rcb-ui.svelte
  src/ui/states/state-error.svelte
  src/ui/states/state-needs-auth-info.svelte
  src/ui/states/state-needs-payment-info.svelte
  src/ui/states/state-success.svelte
  vitest.config.js
Labels: pr:other, pr:force_minor

#325 First proposal to accept branding appearance override
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/behavioural-events/sdk-event-helpers.ts
  src/entities/branding.ts
  src/entities/purchase-params.ts
  src/main.ts
  src/networking/responses/branding-response.ts
  src/stories/fixtures.ts
  src/ui/layout/container.svelte
  src/ui/layout/main-block.svelte
  src/ui/layout/navbar.svelte
  src/ui/states/state-present-offer.svelte
  src/ui/theme/colors.ts
  src/ui/theme/theme.ts
  src/ui/theme/utils.ts
Labels: pr:other

#326 [WEB-2140] restore scroll after closing modal + fixing height
  .env.development
  src/main.ts
  src/stories/purchase-flow-desktop-embedded.stories.svelte
  src/tests/main.test.ts
  src/ui/layout/container.svelte
  src/ui/rcb-ui-inner.svelte
  src/ui/rcb-ui.svelte
Labels: pr:other

#328 WEB-2173: Improvements to the embedded mode
  .env.development
  src/main.ts
  src/stories/purchase-flow-desktop-embedded.stories.svelte
  src/ui/layout/container.svelte
  src/ui/rcb-ui-inner.svelte
Labels: pr:other

#332 [WEB-2141] update link style in error page to primary
  src/ui/states/state-error.svelte
Labels: pr:other

#338 WEB-2236: Rebuilt the state present offer to align with the latest Figma designs
  src/helpers/duration-helper.ts
  src/stories/fixtures.ts
  src/stories/purchase-flow-custom-appearance-desktop-embedded.stories.svelte
  src/stories/purchase-flow-custom-appearance-desktop.stories.svelte
  src/stories/purchase-flow-desktop-embedded.stories.svelte
  src/stories/purchase-flow-desktop.stories.svelte
  src/stripe/stripe-service.ts
  src/tests/helpers/duration-helper.test.ts
  src/tests/helpers/paywall-variables-helper.test.ts
  src/tests/helpers/price-labels.test.ts
  src/ui/button.svelte
  src/ui/layout/navbar.svelte
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/localization/translator.ts
  src/ui/states/state-needs-auth-info.svelte
  src/ui/states/state-needs-payment-info.svelte
  src/ui/states/state-present-offer.svelte
  src/ui/theme/colors.ts
  src/ui/theme/shapes.ts
  src/ui/theme/spacing.ts
  src/ui/theme/text.ts
  src/ui/theme/utils.ts
Labels: pr:feat, pr:breaking

#343 Add `prepaid` entitlement period support
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/entities/customer-info.ts
Labels: pr:fix

#344 WEB-2106: Using 16px input fontSize to avoid ios phones zooming in
  src/stripe/stripe-service.ts
Labels: pr:fix
