Repository RevenueCat/purchases-js, pull requests merged in 2025-04, with the labels that each got.

#420 Use rectangle for fantastic cat branding
  src/stories/fixtures.ts
Labels: pr:other

#418 [WEB-2353] Improve PricingTable style
  src/stories/atoms/skeleton.stories.svelte
  src/stories/pages/purchase.stories.svelte
  src/ui/atoms/skeleton.svelte
  src/ui/molecules/pricing-dropdown.svelte
  src/ui/molecules/pricing-table.svelte
  src/ui/molecules/product-header.svelte
  src/ui/molecules/product-pricing/subscription-pricing.svelte
  src/ui/molecules/secure-checkout-rc.svelte
  src/ui/theme/colors.ts
  src/ui/theme/utils.ts
Labels: pr:other

#426 Add new APIs to CustomerInfo to match our mobile SDKs
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/entities/customer-info.ts
  src/main.ts
  src/networking/responses/subscriber-response.ts
  src/tests/entities/customer-info.test.ts
  src/tests/main.test.ts
  src/tests/test-responses.ts
Labels: pr:feat

#428 Add pricePerWeek/pricePerMonth/pricePerYear APIs to PricingPhase
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/entities/offerings.ts
  src/stories/fixtures.ts
  src/tests/helpers/paywall-variables-helper.test.ts
  src/tests/mocks/offering-mock-provider.ts
  src/tests/purchase.offerings.test.ts
Labels: pr:feat

#431 Update esbuild, vite and vitest in example app to solve security vulnerabilities
  examples/webbilling-demo/package-lock.json
  examples/webbilling-demo/package.json
Labels: pr:other

#436 WEB-2370: Added E2E tests for the tax calculation behaviour
  .circleci/config.yml
  examples/webbilling-demo/package-lock.json
  examples/webbilling-demo/playwright.config.ts
  examples/webbilling-demo/src/tests/main.test.ts
  examples/webbilling-demo/src/tests/tax-calculation.test.ts
  examples/webbilling-demo/src/tests/utils.ts
Labels: pr:other

#438 Disable tax calculation E2E tests based on env var in CircleCI
  .circleci/config.yml
  examples/webbilling-demo/src/tests/constants.ts
  examples/webbilling-demo/src/tests/main.test.ts
  examples/webbilling-demo/src/tests/paywalls-v2.test.ts
Labels: pr:other

#433 [WEB-2398] Do not present taxes to customers in `not_collecting` jurisdictions (FF)
  src/helpers/purchase-operation-helper.ts
  src/stories/fixtures.ts
  src/stories/molecules/pricing-table.stories.svelte
  src/tests/helpers/purchase-operation-helper.test.ts
  src/ui/molecules/pricing-table.svelte
  src/ui/purchases-ui.svelte
Labels: pr:other

#439 chore: isolate tax calculation e2e tests
  .circleci/config.yml
  examples/webbilling-demo/playwright.config.ts
  examples/webbilling-demo/src/tests/tax-calculation.test.ts
  examples/webbilling-demo/src/tests/utils.ts
  examples/webbilling-demo/src/util/PurchasesLoader.ts
Labels: pr:other

#432 WEB-2370 - part 1: Refactored the Stripe Payment Elements component to isolate the Payment Elements part
  src/stories/pages/purchase.stories.svelte
  src/tests/ui/pages/payment-entry-page.test.ts
  src/ui/molecules/stripe-elements.svelte
  src/ui/molecules/stripe-payment-element.svelte
  src/ui/pages/payment-entry-page.svelte
Labels: pr:other

#441 Improvement integration testing
  examples/webbilling-demo/src/tests/helpers/fixtures.ts
  examples/webbilling-demo/src/tests/helpers/test-helpers.ts
  examples/webbilling-demo/src/tests/purchase-flow.test.ts
  examples/webbilling-demo/src/tests/tax-calculation.test.ts
Labels: pr:other

#443 Add an env var for non tax test api key
  examples/webbilling-demo/.env.example
  examples/webbilling-demo/README.md
  examples/webbilling-demo/src/tests/helpers/fixtures.ts
  examples/webbilling-demo/src/tests/helpers/test-helpers.ts
Labels: pr:other

#442 Runes mode on a couple components
  examples/webbilling-demo/src/tests/event-tracking.test.ts
  examples/webbilling-demo/src/tests/helpers/fixtures.ts
  src/stories/fixtures.ts
  src/stories/pages/purchase.stories.svelte
  src/stripe/stripe-service.ts
  src/tests/ui/pages/payment-entry-page.test.ts
  src/ui/molecules/pricing-table.svelte
  src/ui/molecules/stripe-elements.svelte
  src/ui/pages/payment-entry-page.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/purchases-ui.svelte
  src/ui/ui-types.ts
Labels: pr:other

#421 Remove email step
  examples/webbilling-demo/playwright.config.ts
  examples/webbilling-demo/src/tests/helpers/test-helpers.ts
  examples/webbilling-demo/src/tests/localization.test.ts
  examples/webbilling-demo/src/tests/purchase-flow.test.ts
  examples/webbilling-demo/src/tests/tax-calculation.test.ts
  examples/webbilling-demo/src/tests/utm-params-propagation.test.ts
  src/behavioural-events/sdk-event-helpers.ts
  src/behavioural-events/sdk-events.ts
  src/networking/responses/checkout-complete-response.ts
  src/stories/pages/purchase.stories.svelte
  src/stripe/stripe-service.ts
  src/tests/locale/locale.test.ts
  src/tests/test-responses.ts
  src/tests/ui/pages/email-entry-page.test.ts
  src/tests/ui/pages/payment-entry-page.test.ts
  src/tests/ui/purchases-ui.test.ts
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/molecules/stripe-authentication-link-element.svelte
  src/ui/molecules/stripe-elements.svelte
  src/ui/pages/email-entry-page.svelte
  src/ui/pages/error-page.svelte
  src/ui/pages/payment-entry-page.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/purchases-ui.svelte
  src/ui/theme/spacing.ts
  src/ui/ui-types.ts
Labels: pr:feat

#448 Add stories for BrandingInfo
  src/stories/molecules/branding-info.stories.svelte
Labels: pr:other

#446 [WEB-2450] Add PayButton with Wallet
  examples/webbilling-demo/src/tests/tax-calculation.test.ts
  src/assets/info.svg
  src/stories/atoms/icon.stories.svelte
  src/stories/molecules/info-message.stories.svelte
  src/stories/molecules/payment-button.stories.svelte
  src/stories/molecules/price-update-info.stories.svelte
  src/ui/atoms/icon.svelte
  src/ui/atoms/icons/icon-info.svelte
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/molecules/info-message.svelte
  src/ui/molecules/payment-button.svelte
  src/ui/molecules/price-update-info.svelte
Labels: pr:other

#449 [WEB-2430] Update font sizes
  src/stories/atoms/button.stories.svelte
  src/stories/atoms/typography.stories.svelte
  src/stories/fixtures.ts
  src/stories/molecules/branding-info.stories.svelte
  src/stripe/stripe-service.ts
  src/ui/atoms/text-separator.svelte
  src/ui/atoms/typography.svelte
  src/ui/layout/container.svelte
  src/ui/layout/message-layout.svelte
  src/ui/layout/navbar-header.svelte
  src/ui/layout/section-layout.svelte
  src/ui/molecules/back-button.svelte
  src/ui/molecules/branding-info.svelte
  src/ui/molecules/button.svelte
  src/ui/molecules/info-message.svelte
  src/ui/molecules/payment-button.svelte
  src/ui/molecules/pricing-dropdown.svelte
  src/ui/molecules/pricing-summary.svelte
  src/ui/molecules/pricing-table.svelte
  src/ui/molecules/product-header.svelte
  src/ui/molecules/product-pricing/non-subscription-pricing.svelte
  src/ui/molecules/product-pricing/subscription-pricing.svelte
  src/ui/molecules/sandbox-banner.svelte
  src/ui/molecules/secure-checkout-rc.svelte
  src/ui/organisms/product-info.svelte
  src/ui/theme/spacing.ts
  src/ui/theme/text.ts
  src/ui/theme/utils.ts
Labels: pr:other

#444 refactor: Simplify Stripe integration and improve error handling
  examples/webbilling-demo/src/tests/helpers/test-helpers.ts
  examples/webbilling-demo/src/tests/tax-calculation.test.ts
  src/stories/pages/purchase.stories.svelte
  src/stripe/stripe-service.ts
  src/tests/stripe/stripe-service.test.ts
  src/tests/ui/pages/payment-entry-page.test.ts
  src/ui/layout/message-layout.svelte
  src/ui/molecules/pricing-table.svelte
  src/ui/molecules/stripe-authentication-link-element.svelte
  src/ui/molecules/stripe-elements.svelte
  src/ui/molecules/stripe-payment-element.svelte
  src/ui/pages/error-page.svelte
  src/ui/pages/payment-entry-page.svelte
  src/ui/pages/success-page.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/purchases-ui.svelte
  src/ui/types/payment-element-error.ts
  src/ui/ui-types.ts
Labels: pr:other

#450 [WEB-2424] Trigger a tax calculation upon payment submission
  examples/webbilling-demo/src/tests/constants.ts
  examples/webbilling-demo/src/tests/helpers/fixtures.ts
  examples/webbilling-demo/src/tests/tax-calculation.test.ts
  src/stories/fixtures.ts
  src/stories/molecules/payment-button.stories.svelte
  src/stories/molecules/price-update-info.stories.svelte
  src/stories/pages/purchase.stories.svelte
  src/stripe/stripe-service.ts
  src/tests/ui/pages/payment-entry-page.test.ts
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/molecules/info-message.svelte
  src/ui/molecules/payment-button.svelte
  src/ui/molecules/price-update-info.svelte
  src/ui/molecules/pricing-table.svelte
  src/ui/molecules/stripe-authentication-link-element.svelte
  src/ui/molecules/stripe-elements.svelte
  src/ui/molecules/stripe-payment-element.svelte
  src/ui/pages/payment-entry-page.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/ui-types.ts
Labels: pr:other

#454 A few minor text style fixes
  src/ui/atoms/typography.svelte
  src/ui/molecules/secure-checkout-rc.svelte
  src/ui/theme/text.ts
Labels: pr:other, pr:RevenueCatUI

#451 [WEB-2436] Update header and fix spacing
  src/stories/atoms/app-logo.stories.svelte
  src/stories/atoms/button.stories.svelte
  src/stories/atoms/icon.stories.svelte
  src/stories/atoms/processing-animation.stories.svelte
  src/stories/atoms/skeleton.stories.svelte
  src/stories/atoms/spinner.stories.svelte
  src/stories/atoms/typography.stories.svelte
  src/stories/decorators/layout-decorators.ts
  src/stories/decorators/storybook-layout.svelte
  src/stories/decorators/with-layout.svelte
  src/stories/decorators/with-layout.ts
  src/stories/decorators/with-navbar.svelte
  src/stories/decorators/with-navbar.ts
  src/stories/molecules/back-button.stories.svelte
  src/stories/molecules/branding-header.stories.svelte
  src/stories/molecules/close-button.stories.svelte
  src/stories/molecules/info-message.stories.svelte
  src/stories/molecules/payment-button.stories.svelte
  src/stories/molecules/price-update-info.stories.svelte
  src/stories/molecules/pricing-dropdown.stories.svelte
  src/stories/molecules/pricing-summary.stories.svelte
  src/stories/molecules/pricing-table.stories.svelte
  src/stories/molecules/product-header.stories.svelte
  src/stories/molecules/secure-checkout-rc.stories.svelte
  src/stories/organisms/product-info.stories.svelte
  src/stories/pages/purchase.stories.svelte
  src/stripe/stripe-service.ts
  src/ui/atoms/app-logo.svelte
  src/ui/atoms/icon.svelte
  src/ui/atoms/icons/icon-back.svelte
  src/ui/atoms/icons/icon-close.svelte
  src/ui/layout/main-block.svelte
  src/ui/layout/navbar.svelte
  src/ui/layout/section-layout.svelte
  src/ui/layout/template.svelte
  src/ui/molecules/back-button.svelte
  src/ui/molecules/branding-header.svelte
  src/ui/molecules/branding-info.svelte
  src/ui/molecules/close-button.svelte
  src/ui/molecules/pricing-dropdown.svelte
  src/ui/molecules/pricing-table.svelte
  src/ui/molecules/product-header.svelte
  src/ui/molecules/stripe-elements.svelte
  src/ui/organisms/product-info.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/theme/spacing.ts
  src/ui/theme/text.ts
Labels: pr:other, pr:RevenueCatUI

#457 Explicit align of header
  src/ui/molecules/branding-header.svelte
Labels: pr:other, pr:RevenueCatUI

#453 [WEB-2480] Button to component lib
  package-lock.json
  package.json
  src/stories/atoms/button.stories.svelte
  src/stories/atoms/processing-animation.stories.svelte
  src/ui/atoms/processing-animation.svelte
  src/ui/layout/message-layout.svelte
  src/ui/molecules/button.svelte
  src/ui/molecules/payment-button.svelte
Labels: pr:dependencies
