Repository RevenueCat/purchases-js, pull requests merged in 2025-01, with the labels that each got.

#275 chore: add console.error in example app when API is not set
  examples/rcbilling-demo/src/util/PurchasesLoader.ts
Labels: pr:other

#276 chore: upgrade storybook to latest
  package-lock.json
  package.json
Labels: pr:other

#284 Quieter test logs
  src/tests/test-responses.ts
  src/ui/localization/translator.ts
Labels: pr:other

#273 Track simple SDK_INITIALIZED event
  Gemfile.lock
  examples/rcbilling-demo/package-lock.json
  examples/rcbilling-demo/src/tests/main.test.ts
  package-lock.json
  package.json
  src/behavioural-events/events-tracker.ts
  src/behavioural-events/events.ts
  src/behavioural-events/flush-manager.ts
  src/main.ts
  src/networking/http-client.ts
  src/tests/base.purchases_test.ts
  src/tests/events.test.ts
  src/tests/flush-manager.test.ts
  src/tests/main.test.ts
  src/tests/test-responses.ts
  src/tests/utils/to-have-been-called-exactly-once-with.ts
  src/tests/vitest.d.ts
  src/ui/localization/translator.ts
Labels: pr:feat

#283 [WEB-2016] Rename Web Billing
  .circleci/config.yml
  README.md
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/webbilling-demo/.env.example
  examples/webbilling-demo/.eslintrc.config.js
  examples/webbilling-demo/.gitignore
  examples/webbilling-demo/.prettierignore
  examples/webbilling-demo/.prettierrc
  examples/webbilling-demo/README.md
  examples/webbilling-demo/index.html
  examples/webbilling-demo/package-lock.json
  examples/webbilling-demo/package.json
  examples/webbilling-demo/playwright-global-setup.ts
  examples/webbilling-demo/playwright.config.ts
  examples/webbilling-demo/public/screenshot.png
  examples/webbilling-demo/public/vite.svg
  examples/webbilling-demo/src/App.css
  examples/webbilling-demo/src/App.tsx
  examples/webbilling-demo/src/Loader/index.tsx
  examples/webbilling-demo/src/Loader/nyan-cat.gif
  examples/webbilling-demo/src/components/AppLogo.tsx
  examples/webbilling-demo/src/components/AppStoreButton.tsx
  examples/webbilling-demo/src/components/Button.tsx
  examples/webbilling-demo/src/components/IChildrenProps.ts
  examples/webbilling-demo/src/components/LogoutButton.tsx
  examples/webbilling-demo/src/components/PlayStoreButton.tsx
  examples/webbilling-demo/src/components/WithEntitlement.tsx
  examples/webbilling-demo/src/components/WithoutEntitlement.tsx
  examples/webbilling-demo/src/main.tsx
  examples/webbilling-demo/src/pages/landingPage/index.tsx
  examples/webbilling-demo/src/pages/login/index.tsx
  examples/webbilling-demo/src/pages/paywall/index.tsx
  examples/webbilling-demo/src/pages/rc_paywall/index.tsx
  examples/webbilling-demo/src/pages/success/index.tsx
  examples/webbilling-demo/src/tests/main.test.ts
  examples/webbilling-demo/src/util/PurchasesLoader.ts
  examples/webbilling-demo/src/vite-env.d.ts
  examples/webbilling-demo/tsconfig.json
  examples/webbilling-demo/tsconfig.node.json
  examples/webbilling-demo/vite.config.ts
  src/entities/customer-info.ts
  src/entities/offerings.ts
  src/helpers/configuration-validators.ts
  src/helpers/offerings-parser.ts
  src/helpers/paywall-variables-helpers.ts
  src/main.ts
  src/tests/helpers/paywall-variables-helper.test.ts
  src/tests/mocks/offering-mock-provider.ts
  src/tests/purchase.offerings.test.ts
  src/ui/rcb-ui.svelte
Labels: pr:other, pr:force_minor

#285 [WEB-1910] Track checkout session start event
  api-report/purchases-js.api.json
  examples/rcbilling-demo/src/tests/main.test.ts
  src/behavioural-events/events-tracker.ts
  src/behavioural-events/events.ts
  src/helpers/camel-to-underscore.ts
  src/main.ts
  src/tests/base.purchases_test.ts
  src/tests/behavioral-events/events-tracker.test.ts
  src/tests/events.test.ts
  src/ui/rcb-ui.svelte
Labels: pr:other

#287 [WEB-1911] Track billing email entry events
  .circleci/config.yml
  README.md
  package-lock.json
  package.json
  src/behavioural-events/events-tracker.ts
  src/behavioural-events/events.ts
  src/entities/http-config.ts
  src/main.ts
  src/stories/fixtures.ts
  src/tests/behavioral-events/events-tracker.test.ts
  src/tests/behavioral-events/flush-manager.test.ts
  src/tests/entities/customer-info.test.ts
  src/tests/events.test.ts
  src/tests/purchase.events.ts
  src/tests/ui/purchases-ui.test.ts
  src/ui/close-button.svelte
  src/ui/constants.ts
  src/ui/rcb-ui.svelte
  src/ui/states/state-needs-auth-info.svelte
Labels: pr:other
