Repository RevenueCat/purchases-js, pull requests merged in 2025-05, with the labels that each got.

#464 Fixed modal errors appearing below the form on mobile
  src/ui/pages/payment-entry-page.svelte
Labels: pr:fix

#467 feat: Add support to Stripe Express checkout
  examples/webbilling-demo/src/tests/helpers/test-helpers.ts
  src/stories/pages/purchase.stories.svelte
  src/stripe/stripe-service.ts
  src/ui/atoms/text-separator.svelte
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/molecules/stripe-elements.svelte
  src/ui/molecules/stripe-express-checkout-element.svelte
  src/ui/pages/payment-entry-page.svelte
Labels: pr:feat

#465 Remove unneeded payment-entry-processing enum value
  src/ui/pages/payment-entry-page.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/purchases-ui.svelte
  src/ui/ui-types.ts
Labels: pr:other

#471 Exposed the possibility of customizing the labels as internal parameter
  examples/webbilling-demo/src/pages/paywall/index.tsx
  package-lock.json
  src/entities/purchase-params.ts
  src/main.ts
  src/ui/molecules/payment-button.svelte
Labels: pr:feat

#472 Render wordmark when possible
  src/networking/responses/branding-response.ts
  src/stories/atoms/app-wordmark.stories.svelte
  src/stories/fixtures.ts
  src/ui/atoms/app-wordmark.svelte
  src/ui/molecules/branding-header.svelte
Labels: pr:feat

#474 Track rcSource
  src/behavioural-events/events-tracker.ts
  src/behavioural-events/sdk-event-context.ts
  src/entities/flags-config.ts
  src/main.ts
  src/tests/base.purchases_test.ts
  src/tests/behavioral-events/events-tracker.test.ts
  src/tests/behavioral-events/sdk-event-context.test.ts
  src/tests/purchase.events.test.ts
Labels: pr:other

#475 Hide back button when coming from app
  src/main.ts
  src/stories/pages/purchase.stories.svelte
  src/ui/purchases-ui-inner.svelte
Labels: pr:other

#476 Support branded fonts in typography
  src/networking/responses/branding-response.ts
  src/stories/atoms/typography.stories.svelte
  src/stories/fixtures.ts
  src/ui/atoms/typography.svelte
  src/ui/layout/container.svelte
  src/ui/layout/template.svelte
  src/ui/molecules/product-header.svelte
  src/ui/theme/text.ts
  src/ui/theme/theme.ts
  src/ui/theme/utils.ts
Labels: pr:feat

#477 Increase top padding in mobile + Fix sandbox Close button
  src/ui/atoms/icons/icon-close.svelte
  src/ui/molecules/branding-header.svelte
  src/ui/molecules/sandbox-banner.svelte
Labels: pr:feat

#486 Remove unused stripe styles
  src/stripe/stripe-service.ts
Labels: pr:other

#495 Fix flakey Email Deliverability test
  examples/webbilling-demo/src/tests/helpers/test-helpers.ts
Labels: pr:other

#490 [WEB-2475] Better errors for Stripe setup on sandbox
  examples/webbilling-demo/src/tests/helpers/test-helpers.ts
  examples/webbilling-demo/src/tests/tax-calculation.test.ts
  scripts/translate_locales.py
  src/entities/errors.ts
  src/helpers/purchase-operation-helper.ts
  src/stories/fixtures.ts
  src/stories/pages/error-page.stories.svelte
  src/tests/locale/locale.test.ts
  src/ui/atoms/skeleton.svelte
  src/ui/layout/message-layout.svelte
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/pages/error-page.svelte
Labels: pr:other

#492 Fix flickering button when taxes are being refreshed
  examples/webbilling-demo/src/tests/helpers/test-helpers.ts
  examples/webbilling-demo/src/tests/tax-calculation.test.ts
  src/helpers/purchase-operation-helper.ts
  src/networking/backend.ts
  src/networking/http-client.ts
  src/tests/locale/locale.test.ts
  src/ui/pages/payment-entry-page.svelte
  src/ui/ui-types.ts
Labels: pr:fix

#496 Remove pending reason
  src/stories/fixtures.ts
  src/stories/molecules/pricing-table.stories.svelte
  src/ui/molecules/pricing-table.svelte
  src/ui/pages/payment-entry-page.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/ui-types.ts
Labels: pr:other

#416 [WEBF-4] Support subscriber attributes
  .gitignore
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  examples/webbilling-demo/src/App.css
  examples/webbilling-demo/src/pages/login/index.tsx
  examples/webbilling-demo/src/pages/paywall/index.tsx
  examples/webbilling-demo/src/tests/attributes.test.ts
  examples/webbilling-demo/src/tests/helpers/test-helpers.ts
  package-lock.json
  src/entities/attributes.ts
  src/entities/errors.ts
  src/main.ts
  src/networking/backend.ts
  src/networking/endpoints.ts
  src/networking/http-client.ts
  src/tests/base.purchases_test.ts
  src/tests/main.test.ts
  src/tests/networking/backend.test.ts
  src/tests/networking/endpoints.test.ts
  vitest.config.js
Labels: pr:feat

#499 Fix tax calculation mistakenly launched
  src/ui/pages/payment-entry-page.svelte
Labels: pr:fix

#501 Fix e2e test app user ID generation
  examples/webbilling-demo/src/pages/paywall/index.tsx
  examples/webbilling-demo/src/tests/helpers/test-helpers.ts
Labels: pr:other

#502 [WEB-2563] Improve robustness on integration tests
  examples/webbilling-demo/package-lock.json
  examples/webbilling-demo/src/tests/helpers/integration-test.ts
  examples/webbilling-demo/src/tests/helpers/test-helpers.ts
  examples/webbilling-demo/src/tests/tax-calculation.test.ts
Labels: pr:other

#503 Fix concurrent call in `StrictMode`
  examples/webbilling-demo/src/pages/paywall/index.tsx
  package-lock.json
Labels: pr:other

#494 only load Stripe when calling .purchase()
  src/stripe/stripe-service.ts
Labels: bug, pr:fix

#509 [PSP-189] Allow Paddle Api key on validation
  src/helpers/configuration-validators.ts
Labels: pr:other

#505 @gezquinndesign: fix: save and apply original inline styles on close (#484)
  src/tests/ui/purchases-ui.test.ts
  src/ui/purchases-ui.svelte
Labels: bug, pr:fix

#514 WEB-2643: Do not show recurrent payment message for one-time purchases
  src/stories/fixtures.ts
  src/stories/molecules/secure-checkout-rc.stories.svelte
  src/stories/pages/payment-entry-page.stories.svelte
  src/ui/molecules/secure-checkout-rc.svelte
Labels: pr:fix
