Repository RevenueCat/purchases-js, pull requests merged in 2025-03, with the labels that each got.

#351 [WEB-2237] Add the trial information text below the checkout form
  scripts/translate_locales.py
  src/stories/purchase-flow-mobile.stories.svelte
  src/stripe/stripe-service.ts
  src/ui/localization/keys_context.json
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/secure-checkout-rc.svelte
  src/ui/states/state-needs-payment-info.svelte
Labels: pr:fix

#350 [WEB-2013] chore: Add calculate taxes endpoint
  src/helpers/purchase-operation-helper.ts
  src/networking/backend.ts
  src/networking/endpoints.ts
  src/networking/responses/branding-response.ts
  src/networking/responses/checkout-calculate-taxes-response.ts
  src/stories/fixtures.ts
Labels: pr:other

#359 Added the collectAnalyticsEvents parameter
  api-report/purchases-js.api.json
  api-report/purchases-js.api.md
  src/behavioural-events/events-tracker.ts
  src/entities/flags-config.ts
  src/main.ts
  src/tests/behavioral-events/events-tracker.test.ts
  src/ui/states/state-needs-auth-info.svelte
Labels: pr:feat

#362 Only show "Details" button when we need to
  src/ui/layout/navbar.svelte
  src/ui/navbar-header.svelte
  src/ui/rcb-ui-inner.svelte
Labels: pr:fix

#361 "Details" button fixes
  src/ui/layout/navbar.svelte
  src/ui/localization/keys_context.json
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/navbar-header.svelte
  src/ui/rcb-ui-inner.svelte
  src/ui/states/state-present-offer.svelte
  src/ui/theme/text.ts
Labels: pr:fix

#363 [WEB-2291] sdk in the tablet the margins are too big
  src/ui/layout/section-layout.svelte
  src/ui/theme/spacing.ts
  src/ui/theme/utils.ts
Labels: pr:fix

#365 upgrade vitest to 2.1.9
  package-lock.json
Labels: pr:fix

#366 Use inputmode=email to prompt friendly keyboard
  src/ui/states/state-needs-auth-info.svelte
Labels: pr:other

#369 Release/1.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  package.json
  scripts/docs/index.html
  src/helpers/constants.ts
Labels: pr:next_release

#370 Upgrade vitest to 2.1.9
  examples/webbilling-demo/package-lock.json
  examples/webbilling-demo/package.json
  package-lock.json
  package.json
Labels: pr:fix

#372 WEB-2327: Added a close and a back button when not in element
  scripts/translate_locales.py
  src/assets/close.svg
  src/stories/purchase-flow-custom-appearance-desktop.stories.svelte
  src/ui/back-button.svelte
  src/ui/branding-info-ui.svelte
  src/ui/close-button.svelte
  src/ui/icons/icon-arrow.svelte
  src/ui/layout/navbar.svelte
  src/ui/localization/keys_context.json
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/navbar-header.svelte
  src/ui/rcb-ui-inner.svelte
  src/ui/rcb-ui.svelte
  src/ui/sandbox-banner.svelte
  src/ui/states/state-present-offer.svelte
Labels: pr:fix

#377 WEB-2336: Adjusted the gaps and moved the product description below the title
  src/stories/purchase-flow-custom-appearance-mobile.stories.svelte
  src/ui/states/state-present-offer.svelte
Labels: pr:fix

#374 Storybook with globals
  .storybook/main.ts
  .storybook/modes.ts
  .storybook/preview.ts
  package-lock.json
  src/networking/responses/branding-response.ts
  src/stories/button.stories.svelte
  src/stories/components.stories.svelte
  src/stories/fixtures.ts
  src/stories/icons.stories.svelte
  src/stories/purchase-flow-custom-appearance-desktop-embedded.stories.svelte
  src/stories/purchase-flow-custom-appearance-desktop.stories.svelte
  src/stories/purchase-flow-custom-appearance-mobile.stories.svelte
  src/stories/purchase-flow-desktop-embedded.stories.svelte
  src/stories/purchase-flow-desktop.stories.svelte
  src/stories/purchase-flow-mobile.stories.svelte
  src/stories/purchase-flow-rtl.stories.svelte
  src/stories/purchase-flow-tablet.stories.svelte
  src/stories/purchase-flow.stories.svelte
  src/stories/utils/global-decorator.svelte
  src/stories/utils/with-layout-decorator.ts
  src/stories/utils/with-layout.svelte
  src/tests/ui/states/state-needs-auth-info.test.ts
  src/tests/ui/states/state-needs-payment-info.test.ts
  src/tests/ui/states/state-success.test.ts
  src/ui/icon.svelte
  src/ui/layout/container.svelte
  src/ui/layout/main-block.svelte
  src/ui/layout/navbar.svelte
  src/ui/localization/localized.svelte
  src/ui/rcb-ui.svelte
  src/ui/states/state-error.svelte
  src/ui/states/state-needs-auth-info.svelte
  src/ui/states/state-needs-payment-info.svelte
  src/ui/states/state-present-offer.svelte
  src/ui/states/state-success.svelte
Labels: pr:other

#381 Fix translations for `price_after_free_trial`
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
Labels: pr:fix

#383 Fix variables translation miss-matches
  src/tests/locale/locale.test.ts
  src/ui/localization/locale/ja.json
Labels: pr:fix

#386 Fix tracking selected_payment_method
  src/tests/ui/states/state-needs-payment-info.test.ts
  src/ui/states/state-needs-payment-info.svelte
Labels: pr:fix

#379 Add support for pseudo-states on the storybook toolbar
  .storybook/main.ts
  package-lock.json
  package.json
Labels: pr:other

#380 Extract pricing components and stories
  .storybook/modes.ts
  src/stories/button.stories.svelte
  src/stories/fixtures.ts
  src/stories/icons.stories.svelte
  src/stories/product-info-header.stories.svelte
  src/stories/product-info-pricing.stories.svelte
  src/stories/utils/decorators.ts
  src/stories/utils/with-layout-decorator.ts
  src/stories/utils/with-navbar.svelte
  src/ui/components/product-info-header.svelte
  src/ui/components/product-info-pricing.svelte
  src/ui/states/state-present-offer.svelte
Labels: pr:other

#391 Freeze storybook date
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
Labels: pr:other

#389 Reorganize components
  src/main.ts
  src/stories/button.stories.svelte
  src/stories/icon.stories.svelte
  src/stories/product-info-header.stories.svelte
  src/stories/product-info-pricing.stories.svelte
  src/stories/purchase-flow.stories.svelte
  src/stories/utils/get-story-checkout-args.ts
  src/stories/utils/with-layout.svelte
  src/tests/ui/purchases-ui.test.ts
  src/ui/components/app-logo.svelte
  src/ui/components/back-button.svelte
  src/ui/components/badge.svelte
  src/ui/components/branding-info.svelte
  src/ui/components/button.svelte
  src/ui/components/close-button.svelte
  src/ui/components/icon.svelte
  src/ui/components/icons/icon-arrow.svelte
  src/ui/components/icons/icon-cart.svelte
  src/ui/components/icons/icon-error.svelte
  src/ui/components/icons/icon-lock.svelte
  src/ui/components/icons/icon-success.svelte
  src/ui/components/processing-animation.svelte
  src/ui/components/product-info.svelte
  src/ui/components/product-info/header.svelte
  src/ui/components/product-info/pricing.svelte
  src/ui/components/sandbox-banner.svelte
  src/ui/components/secure-checkout-rc.svelte
  src/ui/components/spinner.svelte
  src/ui/components/text-separator.svelte
  src/ui/layout/message-layout.svelte
  src/ui/layout/modal-footer.svelte
  src/ui/layout/modal-section.svelte
  src/ui/layout/navbar-header.svelte
  src/ui/layout/navbar.svelte
  src/ui/localization/supportedLanguages.ts
  src/ui/purchases-ui-inner.svelte
  src/ui/purchases-ui.svelte
  src/ui/states/state-error.svelte
  src/ui/states/state-loading.svelte
  src/ui/states/state-needs-auth-info.svelte
  src/ui/states/state-needs-payment-info.svelte
  src/ui/states/state-success.svelte
Labels: pr:other

#390 fix: improve anonymous AppUserID generation compatibility for mobile browsers
  src/helpers/uuid-helper.ts
  src/main.ts
  src/tests/main.test.ts
Labels: bug, pr:fix

#393 Improve development setup
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  package.json
Labels: pr:other

#392 Chromatic Diff Threshold
  src/stories/purchase-flow.stories.svelte
Labels: pr:other

#368 Validate app user id on change
  src/main.ts
  src/tests/main.test.ts
Labels: pr:fix

#404 Extract StripePaymentElements
  src/networking/responses/checkout-start-response.ts
  src/stripe/stripe-service.ts
  src/tests/ui/states/state-needs-payment-info.test.ts
  src/ui/molecules/stripe-payment-elements.svelte
  src/ui/states/state-needs-payment-info.svelte
  src/ui/types/payment-element-error.ts
Labels: pr:other

#399 [WEB-2287] Add PricingDropdown
  .storybook/modes.ts
  .storybook/preview.ts
  src/stories/atoms/icon.stories.svelte
  src/stories/molecules/pricing-dropdown.stories.svelte
  src/ui/atoms/icon.svelte
  src/ui/atoms/icons/icon-chevron.svelte
  src/ui/layout/navbar-header.svelte
  src/ui/layout/navbar.svelte
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/molecules/back-button.svelte
  src/ui/molecules/pricing-dropdown.svelte
  src/ui/purchases-ui-inner.svelte
Labels: pr:other

#400 [WEB-2287] Add PricingTable
  src/stories/atoms/tax-title.stories.svelte
  src/stories/molecules/pricing-table.stories.svelte
  src/ui/atoms/tax-title.svelte
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/localization/translator.ts
  src/ui/molecules/pricing-table.svelte
Labels: pr:other

#407 Change fixture values for stories
  src/stories/fixtures.ts
Labels: pr:other

#405 Refactor `PurchasesUIInner`
  src/stories/pages/purchase.stories.svelte
  src/ui/layout/template.svelte
  src/ui/molecules/loading.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/purchases-ui.svelte
  src/ui/states/state-error.svelte
  src/ui/states/state-loading.svelte
  src/ui/states/state-needs-payment-info.svelte
  src/ui/states/state-success.svelte
  src/ui/ui-types.ts
Labels: pr:other

#409 [WEB-2013] Trigger initial tax calculation (FF)
  src/helpers/purchase-operation-helper.ts
  src/networking/backend.ts
  src/networking/endpoints.ts
  src/networking/responses/branding-response.ts
  src/networking/responses/checkout-calculate-tax-response.ts
  src/networking/responses/checkout-calculate-taxes-response.ts
  src/networking/responses/checkout-start-response.ts
  src/networking/responses/stripe-elements.ts
  src/stories/fixtures.ts
  src/stories/molecules/pricing-table.stories.svelte
  src/stories/pages/purchase.stories.svelte
  src/stripe/stripe-service.ts
  src/tests/test-responses.ts
  src/tests/ui/purchases-ui.test.ts
  src/tests/ui/states/state-needs-payment-info.test.ts
  src/ui/molecules/pricing-table.svelte
  src/ui/molecules/stripe-payment-elements.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/purchases-ui.svelte
  src/ui/states/state-needs-payment-info.svelte
Labels: pr:other

#402 Extract needs payment info components
  src/stories/molecules/payment-button.stories.svelte
  src/stories/molecules/product-header.stories.svelte
  src/stories/molecules/secure-checkout-rc.stories.svelte
  src/ui/molecules/payment-button.svelte
  src/ui/molecules/secure-checkout-rc.svelte
  src/ui/states/state-needs-payment-info.svelte
Labels: pr:other

#406 Rearrange state components into pages
  README.md
  src/stories/pages/purchase.stories.svelte
  src/tests/locale/locale.test.ts
  src/tests/ui/pages/email-entry-page.test.ts
  src/tests/ui/pages/payment-entry-page.test.ts
  src/tests/ui/pages/success-page.test.ts
  src/ui/localization/keys_context.json
  src/ui/localization/locale/ar.json
  src/ui/localization/locale/ca.json
  src/ui/localization/locale/cs.json
  src/ui/localization/locale/da.json
  src/ui/localization/locale/de.json
  src/ui/localization/locale/el.json
  src/ui/localization/locale/en.json
  src/ui/localization/locale/es.json
  src/ui/localization/locale/fi.json
  src/ui/localization/locale/fr.json
  src/ui/localization/locale/he.json
  src/ui/localization/locale/hi.json
  src/ui/localization/locale/hr.json
  src/ui/localization/locale/hu.json
  src/ui/localization/locale/id.json
  src/ui/localization/locale/it.json
  src/ui/localization/locale/ja.json
  src/ui/localization/locale/ko.json
  src/ui/localization/locale/ms.json
  src/ui/localization/locale/nl.json
  src/ui/localization/locale/no.json
  src/ui/localization/locale/pl.json
  src/ui/localization/locale/pt.json
  src/ui/localization/locale/ro.json
  src/ui/localization/locale/ru.json
  src/ui/localization/locale/sk.json
  src/ui/localization/locale/sv.json
  src/ui/localization/locale/th.json
  src/ui/localization/locale/tr.json
  src/ui/localization/locale/uk.json
  src/ui/localization/locale/vi.json
  src/ui/localization/locale/zh_Hans.json
  src/ui/localization/locale/zh_Hant.json
  src/ui/localization/supportedLanguages.ts
  src/ui/localization/translator.ts
  src/ui/molecules/payment-button.svelte
  src/ui/molecules/secure-checkout-rc.svelte
  src/ui/pages/email-entry-page.svelte
  src/ui/pages/error-page.svelte
  src/ui/pages/payment-entry-loading-page.svelte
  src/ui/pages/payment-entry-page.svelte
  src/ui/pages/success-page.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/purchases-ui.svelte
  src/ui/ui-types.ts
Labels: pr:other

#412 Update story fixtures
  src/stories/fixtures.ts
Labels: pr:other

#414 chore: Put tax calculations behind the `ALLOW_TAX_CALCULATION_FF` feature flag
  .env.development
  .storybook/main.ts
  src/helpers/constants.ts
  src/tests/ui/purchases-ui.test.ts
  src/ui/purchases-ui.svelte
Labels: pr:other

#411 [WEB-2287] Represent tax breakdown within the pricing details (FF)
  src/networking/responses/checkout-calculate-tax-response.ts
  src/stories/atoms/tax-title.stories.svelte
  src/stories/fixtures.ts
  src/stories/molecules/pricing-summary.stories.svelte
  src/stories/molecules/pricing-table.stories.svelte
  src/stories/molecules/product-pricing.stories.svelte
  src/stories/organisms/product-info-with-tax-support.stories.svelte
  src/stories/organisms/product-info.stories.svelte
  src/stories/pages/purchase.stories.svelte
  src/ui/atoms/tax-title.svelte
  src/ui/molecules/pricing-summary.svelte
  src/ui/molecules/pricing-table.svelte
  src/ui/molecules/product-pricing.svelte
  src/ui/organisms/product-info-with-tax-support.svelte
  src/ui/organisms/product-info.svelte
  src/ui/pages/payment-entry-page.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/purchases-ui.svelte
  src/ui/ui-types.ts
Labels: pr:other

#413 [WEB-2013] Recalculate taxes during checkout (FF)
  src/stories/fixtures.ts
  src/stories/pages/purchase.stories.svelte
  src/stripe/stripe-service.ts
  src/tests/ui/pages/payment-entry-page.test.ts
  src/ui/molecules/pricing-table.svelte
  src/ui/molecules/stripe-payment-elements.svelte
  src/ui/pages/payment-entry-page.svelte
  src/ui/purchases-ui-inner.svelte
  src/ui/purchases-ui.svelte
  src/ui/ui-types.ts
Labels: pr:other

#417 fix: Handled submission errors not displayed when tax collection is enabled (FF)
  examples/webbilling-demo/src/tests/main.test.ts
  src/ui/molecules/stripe-payment-elements.svelte
Labels: pr:other

#419 fix: strip out query parameters from pageUrl
  src/behavioural-events/sdk-event-context.ts
  src/tests/behavioral-events/sdk-event-context.test.ts
Labels: pr:fix
